Denysov\UserService\Application\Command\Ping\PingCommand:
  properties:
    full_name:
      - NotBlank: ~
      - Length:
          min: 3
    email:
      - NotBlank: ~
      - Length:
          min: 3