version: "3.8"

services:
  app:
    image: node:22-alpine3.21
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "serve"]
