services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8081:8080"
    networks: [ intranet ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  intranet:
    external: true
