server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    # Главная страница host SPA
    location = / {
        index index.html;
        try_files /host/index.html =404;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Requested-With' always;

    }

    # Поддиректории (например, sign-up/, profile/, ...): просто отдаём напрямую
    location ~ ^/[^/]+/ {
        try_files $uri $uri/ =404;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Requested-With' always;

    }

    # Все js/css/... в корне → ищем в /host/
    location ~* ^/(.+\.(js|css|json|map|png|jpg|woff2?|ttf|svg))$ {
        try_files /host/$1 =404;
    }

    # SPA fallback для Vue/React router (если нужно)
    location / {
        try_files /host/index.html =404;
    }

    # Отключение кеша для dev
    location ~* \.(js|css|json|html|map)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }
}
