version: "3.8"

services:
  nginx-remote:
    image: nginx:latest
    ports:
      - "8100:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default-remote.conf:/etc/nginx/conf.d/default.conf:ro
  nginx-host:
    image: nginx:latest
    ports:
      - "8800:80"
    volumes:
      - ./dist/host:/usr/share/nginx/html:ro
      - ./nginx/default-host.conf:/etc/nginx/conf.d/default.conf:ro
