version: '3.8'

services:
  root-config:
    image: nginx:latest
    container_name: root-config
    ports:
      - "9000:80"
    volumes:
      - ./root-config/dist:/usr/share/nginx/html:ro
      - ./nginx/root-config.conf:/etc/nginx/conf.d/default.conf:ro

  hello-world:
    image: nginx:latest
    container_name: hello-world
    ports:
      - "8500:80"
    volumes:
      - ./hello-world/dist:/usr/share/nginx/html:ro
      - ./nginx/hello-world.conf:/etc/nginx/conf.d/default.conf:ro
