hello:
  path: /
  controller: Denysov\UserService\Delivery\Http\IndexController

view:
  path: /view
  controller: Denysov\UserService\Delivery\Http\ViewController

list:
  path: /list
  controller: Denysov\UserService\Delivery\Http\ListController