hello:
  path: /
  controller: Denysov\UserService\Delivery\Http\Controller\IndexController

view:
  path: /view
  controller: Denysov\UserService\Delivery\Http\Controller\ViewController

list:
  path: /list
  controller: Denysov\UserService\Delivery\Http\Controller\ListController