services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Denysov\UserService\Delivery\Http\Controller\:
    resource: '../src/Delivery/Http/Controller'
    tags: [ 'controller.service_arguments' ]

  Denysov\UserService\Application\:
    resource: '../src/Application/'
