services:
  app:
    build: ./../../infra/docker/php
    restart: unless-stopped
    expose:
      - "8080"
    networks: [ intranet ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-service-app-1.rule=PathPrefix(`/users`)"
      - "traefik.http.routers.user-service-app-1.entrypoints=web"
      - "traefik.http.services.user-service-app-1.loadbalancer.server.port=8080"
      - "traefik.http.routers.user-service-app-1.middlewares=strip-users"
      - "traefik.http.middlewares.strip-users.stripprefix.prefixes=/users"

    environment:
      RR_MAX_REQUESTS: "1000"
      XDEBUG_CONFIG: "client_host=${XDEBUG_REMOTE_HOST} log_level=0 client_port=9005 start_with_request=yes idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=roadrunner"
    volumes:
      - ./:/app
      - ../../libs/core/:/core

networks:
  intranet:
    external: true